/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xingcloud_analytic_xnative_XCNative */

#ifndef _Included_com_xingcloud_analytic_xnative_XCNative
#define _Included_com_xingcloud_analytic_xnative_XCNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xingcloud_analytic_xnative_XCNative
 * Method:    sendReport
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_xingcloud_analytic_xnative_XCNative_sendReport
  (JNIEnv *, jclass, jstring);

JNIEXPORT jint JNICALL Java_com_xingcloud_analytic_xnative_XCNative_sendPageReport
  (JNIEnv *, jclass, jstring);

JNIEXPORT jint JNICALL Java_com_xingcloud_analytic_xnative_XCNative_sendBaseReport
  (JNIEnv *, jclass, jstring,jstring);


JNIEXPORT void JNICALL Java_com_xingcloud_analytic_xnative_XCNative_initCurl
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
